x-py-scripts-template: &python-base
    build: .
    networks:
      - bm_network
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}   
      - NOTION_YEARS_DB_ID=${NOTION_YEARS_DB_ID}
      - NOTION_MONTHS_DB_ID=${NOTION_MONTHS_DB_ID}
      - NOTION_CATEGORIES_DB_ID=${NOTION_CATEGORIES_DB_ID}
      - NOTION_SUBCATEGORIES_DB_ID=${NOTION_SUBCATEGORIES_DB_ID}
      - NOTION_BUDGETS_DB_ID=${NOTION_BUDGETS_DB_ID}
      - NOTION_ACCOUNTS_DB_ID=${NOTION_ACCOUNTS_DB_ID}
      - NOTION_INC_EXP_DB_ID=${NOTION_INC_EXP_DB_ID}

services:
  extract_ntn_years:
    <<: *python-base
    command: python src/extract_ntn_years.py
    container_name: extract_ntn_years

  extract_ntn_inc_exp:
    <<: *python-base
    command: python src/extract_ntn_inc_exp.py
    container_name: extract_ntn_inc_exp
    
networks:
  bm_network:
    driver: bridge
    