x-py-scripts-template: &python-base
    build: .
    profiles: ["manual"] # To not start with a general 'docker compose up'
    networks:
      - bm_network
    volumes:
      - ./src:/app/src
      - ./src:/opt/airflow/src
      - ./data:/app/data
    environment:
      # --- NOTION CONFIG ---
      NOTION_API_KEY:             ${NOTION_API_KEY}
      NOTION_DB_ID_YEARS:         ${NOTION_DB_ID_YEARS}
      NOTION_DB_ID_MONTHS:        ${NOTION_DB_ID_MONTHS}
      NOTION_DB_ID_CATEGORIES:    ${NOTION_DB_ID_CATEGORIES}
      NOTION_DB_ID_SUBCATEGORIES: ${NOTION_DB_ID_SUBCATEGORIES}
      NOTION_DB_ID_BUDGETS:       ${NOTION_DB_ID_BUDGETS}
      NOTION_DB_ID_ACCOUNTS:      ${NOTION_DB_ID_ACCOUNTS}
      NOTION_DB_ID_INC_EXP:       ${NOTION_DB_ID_INC_EXP}
      # --- DATABASE CONFIG ---
      POSTGRES_USER:              ${POSTGRES_USER}
      POSTGRES_PASSWORD:          ${POSTGRES_PASSWORD}
      POSTGRES_DB:                ${POSTGRES_DB}
    depends_on:
      budget-db:
        condition: service_healthy 

x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.1.7}
  environment:
    &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AF_POSTGRES_USER}:${AF_POSTGRES_PASSWORD}@airflow-db/${AF_POSTGRES_DB}
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-api-server:8080/execution/
    AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: b3c07359b1d86bf033b7c0a6d1db929b9654d7939d95db82438b196b6d8005cd     
    AIRFLOW__API_AUTH__JWT_SECRET: 8a1f2b3c4d5e6f7a8b9c0d1e2f3a4b5c8a1f2b3c4d5e6f7a8b9c0d1e2f3a4b5c  
    _PIP_ADDITIONAL_DEPENDENCIES: "pandas sqlalchemy psycopg2-binary requests"

    # For Airflow to see my project variables
    # --- NOTION CONFIG ---
    NOTION_API_KEY:             ${NOTION_API_KEY}
    NOTION_DB_ID_YEARS:         ${NOTION_DB_ID_YEARS}
    NOTION_DB_ID_MONTHS:        ${NOTION_DB_ID_MONTHS}
    NOTION_DB_ID_CATEGORIES:    ${NOTION_DB_ID_CATEGORIES}
    NOTION_DB_ID_SUBCATEGORIES: ${NOTION_DB_ID_SUBCATEGORIES}
    NOTION_DB_ID_BUDGETS:       ${NOTION_DB_ID_BUDGETS}
    NOTION_DB_ID_ACCOUNTS:      ${NOTION_DB_ID_ACCOUNTS}
    NOTION_DB_ID_INC_EXP:       ${NOTION_DB_ID_INC_EXP}
    # --- DATABASE CONFIG ---
    POSTGRES_USER:              ${POSTGRES_USER}
    POSTGRES_PASSWORD:          ${POSTGRES_PASSWORD}
    POSTGRES_DB:                ${POSTGRES_DB}
    POSTGRES_HOST:              budget-db  # My existing budget manager DB container
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/config:/opt/airflow/config    
    - ./airflow/plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src   
    - ./data:/opt/airflow/data  
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - bm_network
  depends_on:
    airflow-db:
      condition: service_healthy


services:
# --- BUDGET MANAGER DATABASE ---
  budget-db:
    image: postgres:18
    container_name: budget_postgres
    networks:
      - bm_network
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_storage:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5   

# --- PYTHON SERVICES ---
  extract_ntn_years:
    <<: *python-base
    command: python src/extract_ntn_years.py
    container_name: extract_ntn_years

  extract_ntn_months:
    <<: *python-base
    command: python src/extract_ntn_months.py
    container_name: extract_ntn_months    

  extract_ntn_categories:
    <<: *python-base
    command: python src/extract_ntn_categories.py
    container_name: extract_ntn_categories   

  extract_ntn_subcategories:
    <<: *python-base
    command: python src/extract_ntn_subcategories.py
    container_name: extract_ntn_subcategories         

  extract_ntn_budgets:
    <<: *python-base
    command: python src/extract_ntn_budgets.py
    container_name: extract_ntn_budgets       

  extract_ntn_accounts:
    <<: *python-base
    command: python src/extract_ntn_accounts.py
    container_name: extract_ntn_accounts        

  extract_ntn_inc_exp:
    <<: *python-base
    command: python src/extract_ntn_inc_exp.py
    container_name: extract_ntn_inc_exp

# --- AIRFLOW SERVICES ---
  airflow-db:
    image: postgres:17-alpine
    container_name: airflow_postgres
    volumes:
      - af_pg_storage:/var/lib/postgresql/data  
    networks:
      - bm_network
    environment:
      POSTGRES_USER:     ${AF_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AF_POSTGRES_PASSWORD}
      POSTGRES_DB:       ${AF_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AF_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-api-server:
    <<: *airflow-common
    command: api-server
    container_name: airflow_webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v2/monitor/health"]      
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always      

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow_scheduler
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always    

  airflow-init:
    <<: *airflow-common
    profiles: ["setup"] # To not start with a general 'docker compose up'
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"    

networks:
  bm_network:
    driver: bridge

volumes:
  pg_storage:
  af_pg_storage: 
