sources:
  - name: 01_src
    database: "{{ env_var('POSTGRES_DB') }}"  
    schema: 01_src
    tables:
      - name: account
      - name: budget
      - name: category
      - name: month
      - name: subcategory
      - name: transaction
      - name: year